INSERT INTO "permissao_global" ("id", "nome_permissao", "descricao", "grupo") VALUES
  (gen_random_uuid(), 'dashboard:visualizar', 'Acessar dashboard principal', 'dashboard'),
  (gen_random_uuid(), 'dashboard:visualizar_metricas_pessoais', 'Ver métricas pessoais', 'dashboard'),
  (gen_random_uuid(), 'dashboard:visualizar_metricas_equipe', 'Ver métricas da equipe', 'dashboard'),
  (gen_random_uuid(), 'dashboard:visualizar_metricas_gerais', 'Ver métricas gerais da corretora', 'dashboard'),
  (gen_random_uuid(), 'vendas:criar_cotacao', 'Criar cotações', 'vendas'),
  (gen_random_uuid(), 'vendas:visualizar_cotacao', 'Visualizar cotações próprias', 'vendas'),
  (gen_random_uuid(), 'vendas:visualizar_todas_cotacoes', 'Visualizar todas as cotações', 'vendas'),
  (gen_random_uuid(), 'vendas:editar_cotacao', 'Editar cotações', 'vendas'),
  (gen_random_uuid(), 'vendas:excluir_cotacao', 'Excluir cotações', 'vendas'),
  (gen_random_uuid(), 'vendas:criar_proposta', 'Criar propostas', 'vendas'),
  (gen_random_uuid(), 'vendas:visualizar_proposta', 'Visualizar propostas próprias', 'vendas'),
  (gen_random_uuid(), 'vendas:visualizar_todas_propostas', 'Visualizar todas as propostas', 'vendas'),
  (gen_random_uuid(), 'vendas:editar_proposta', 'Editar propostas', 'vendas'),
  (gen_random_uuid(), 'vendas:criar_documento_venda', 'Criar documentos de venda', 'vendas'),
  (gen_random_uuid(), 'vendas:visualizar_documento_venda', 'Visualizar documentos próprios', 'vendas'),
  (gen_random_uuid(), 'vendas:visualizar_todos_documentos', 'Visualizar documentos de todos', 'vendas'),
  (gen_random_uuid(), 'vendas:editar_documento_venda', 'Editar documentos de venda', 'vendas'),
  (gen_random_uuid(), 'vendas:cancelar_venda', 'Cancelar vendas', 'vendas'),
  (gen_random_uuid(), 'vendas:criar_endosso', 'Criar endossos', 'vendas'),
  (gen_random_uuid(), 'vendas:visualizar_endosso', 'Visualizar endossos', 'vendas'),
  (gen_random_uuid(), 'vendas:aprovar_endosso', 'Aprovar endossos', 'vendas'),
  (gen_random_uuid(), 'vendas:visualizar_negocios_corretora', 'Acessar módulo de negócios corretora', 'vendas'),
  (gen_random_uuid(), 'vendas:gerenciar_comissoes', 'Gerenciar comissões de documentos', 'vendas'),
  (gen_random_uuid(), 'vendas:gerenciar_locks', 'Desbloquear documentos de outros usuários', 'vendas'),
  (gen_random_uuid(), 'vendas:editar_valor', 'Editar valor de cotações/propostas', 'vendas'),
  (gen_random_uuid(), 'vendas:editar_comissao', 'Editar percentual e valor de comissão', 'vendas'),
  (gen_random_uuid(), 'vendas:aprovar_desconto', 'Aprovar descontos acima do limite padrão', 'vendas'),
  (gen_random_uuid(), 'vendas:visualizar_comissoes_outros', 'Visualizar comissões de outros vendedores', 'vendas'),
  (gen_random_uuid(), 'vendas:editar_documento_aprovado', 'Editar documento já aprovado pelo cadastro', 'vendas'),
  (gen_random_uuid(), 'vendas:cancelar_venda_efetivada', 'Cancelar venda já efetivada', 'vendas'),
  (gen_random_uuid(), 'cadastro:acessar', 'Acessar módulo de cadastro', 'cadastro'),
  (gen_random_uuid(), 'cadastro:visualizar_pendentes', 'Ver vendas pendentes de cadastro', 'cadastro'),
  (gen_random_uuid(), 'cadastro:validar_documentos', 'Validar documentação de vendas', 'cadastro'),
  (gen_random_uuid(), 'cadastro:aprovar_venda', 'Aprovar vendas', 'cadastro'),
  (gen_random_uuid(), 'cadastro:aprovar_endosso', 'Aprovar e recusar endossos', 'cadastro'),
  (gen_random_uuid(), 'cadastro:rejeitar_venda', 'Rejeitar vendas', 'cadastro'),
  (gen_random_uuid(), 'cadastro:editar_apolice', 'Editar dados de apólice', 'cadastro'),
  (gen_random_uuid(), 'clientes:criar', 'Criar clientes', 'clientes'),
  (gen_random_uuid(), 'clientes:visualizar', 'Visualizar clientes próprios', 'clientes'),
  (gen_random_uuid(), 'clientes:visualizar_todos', 'Visualizar todos os clientes', 'clientes'),
  (gen_random_uuid(), 'clientes:editar', 'Editar clientes', 'clientes'),
  (gen_random_uuid(), 'clientes:excluir', 'Excluir clientes', 'clientes'),
  (gen_random_uuid(), 'clientes:transferir_carteira', 'Transferir carteira de clientes', 'clientes'),
  (gen_random_uuid(), 'clientes:exportar', 'Exportar lista de clientes', 'clientes'),
  (gen_random_uuid(), 'clientes:editar_dados_basicos', 'Editar dados básicos dos clientes (nome, contato)', 'clientes'),
  (gen_random_uuid(), 'clientes:editar_dados_financeiros', 'Editar dados financeiros dos clientes', 'clientes'),
  (gen_random_uuid(), 'clientes:visualizar_cpf_completo', 'Visualizar CPF completo (vs. parcialmente oculto)', 'clientes'),
  (gen_random_uuid(), 'clientes:visualizar_dados_sensiveis', 'Visualizar dados sensíveis completos', 'clientes'),
  (gen_random_uuid(), 'renovacoes:acessar', 'Acessar módulo de renovações', 'renovacoes'),
  (gen_random_uuid(), 'renovacoes:visualizar', 'Visualizar renovações', 'renovacoes'),
  (gen_random_uuid(), 'renovacoes:gerenciar', 'Gerenciar processo de renovação', 'renovacoes'),
  (gen_random_uuid(), 'metricas:acessar', 'Acessar módulo de métricas', 'metricas'),
  (gen_random_uuid(), 'metricas:visualizar_pessoais', 'Ver métricas pessoais detalhadas', 'metricas'),
  (gen_random_uuid(), 'metricas:visualizar_equipe', 'Ver métricas da equipe', 'metricas'),
  (gen_random_uuid(), 'metricas:visualizar_gerais', 'Ver métricas gerais da corretora', 'metricas'),
  (gen_random_uuid(), 'metricas:comparar_vendedores', 'Comparar performance entre vendedores', 'metricas'),
  (gen_random_uuid(), 'relatorios:acessar', 'Acessar módulo de relatórios', 'relatorios'),
  (gen_random_uuid(), 'relatorios:vendas', 'Gerar relatórios de vendas', 'relatorios'),
  (gen_random_uuid(), 'relatorios:comissoes', 'Gerar relatórios de comissões', 'relatorios'),
  (gen_random_uuid(), 'relatorios:financeiro', 'Gerar relatórios financeiros', 'relatorios'),
  (gen_random_uuid(), 'relatorios:producao', 'Gerar relatórios de produção', 'relatorios'),
  (gen_random_uuid(), 'relatorios:exportar', 'Exportar relatórios', 'relatorios'),
  (gen_random_uuid(), 'relatorios:visualizar_comissoes', 'Ver comissões nos relatórios', 'relatorios'),
  (gen_random_uuid(), 'relatorios:exportar_dados_sensiveis', 'Exportar relatórios com dados sensíveis', 'relatorios'),
  (gen_random_uuid(), 'relatorios:comparar_vendedores', 'Comparar performance entre vendedores', 'relatorios'),
  (gen_random_uuid(), 'usuarios:acessar', 'Acessar módulo de usuários', 'usuarios'),
  (gen_random_uuid(), 'usuarios:criar', 'Criar usuários', 'usuarios'),
  (gen_random_uuid(), 'usuarios:visualizar', 'Visualizar usuários', 'usuarios'),
  (gen_random_uuid(), 'usuarios:editar', 'Editar usuários', 'usuarios'),
  (gen_random_uuid(), 'usuarios:excluir', 'Excluir usuários', 'usuarios'),
  (gen_random_uuid(), 'usuarios:resetar_senha', 'Resetar senha de usuários', 'usuarios'),
  (gen_random_uuid(), 'usuarios:atribuir_cargo', 'Atribuir cargos a usuários', 'usuarios'),
  (gen_random_uuid(), 'usuarios:visualizar_equipe_completa', 'Visualizar todos os membros da corretora (não apenas sua equipe)', 'usuarios'),
  (gen_random_uuid(), 'usuarios:transferir_carteira', 'Transferir carteira de clientes entre vendedores', 'usuarios'),
  (gen_random_uuid(), 'usuarios:definir_metas', 'Definir metas para vendedores', 'usuarios'),
  (gen_random_uuid(), 'cargos:criar', 'Criar cargos personalizados', 'cargos'),
  (gen_random_uuid(), 'cargos:visualizar', 'Visualizar cargos', 'cargos'),
  (gen_random_uuid(), 'cargos:editar', 'Editar cargos', 'cargos'),
  (gen_random_uuid(), 'cargos:excluir', 'Excluir cargos', 'cargos'),
  (gen_random_uuid(), 'cargos:atribuir_permissoes', 'Gerenciar permissões de cargos', 'cargos'),
  (gen_random_uuid(), 'equipes:criar', 'Criar equipes', 'equipes'),
  (gen_random_uuid(), 'equipes:visualizar', 'Visualizar equipes', 'equipes'),
  (gen_random_uuid(), 'equipes:editar', 'Editar equipes', 'equipes'),
  (gen_random_uuid(), 'equipes:excluir', 'Excluir equipes', 'equipes'),
  (gen_random_uuid(), 'equipes:gerenciar_membros', 'Gerenciar membros de equipes', 'equipes'),
  (gen_random_uuid(), 'produtos:visualizar', 'Visualizar produtos', 'produtos'),
  (gen_random_uuid(), 'produtos:criar', 'Criar produtos', 'produtos'),
  (gen_random_uuid(), 'produtos:editar', 'Editar produtos', 'produtos'),
  (gen_random_uuid(), 'produtos:excluir', 'Excluir produtos', 'produtos'),
  (gen_random_uuid(), 'seguradoras_parceiras:visualizar', 'Visualizar seguradoras parceiras', 'produtos'),
  (gen_random_uuid(), 'seguradoras_parceiras:gerenciar', 'Gerenciar seguradoras parceiras', 'produtos'),
  (gen_random_uuid(), 'config:acessar', 'Acessar configurações', 'configuracoes'),
  (gen_random_uuid(), 'config:editar_seguradora', 'Editar dados da corretora', 'configuracoes'),
  (gen_random_uuid(), 'config:gerenciar_integracao', 'Gerenciar integrações', 'configuracoes'),
  (gen_random_uuid(), 'config:visualizar_auditoria', 'Visualizar logs de auditoria', 'configuracoes'),
  (gen_random_uuid(), 'workspace:acessar', 'Acessar Área de Trabalho', 'workspace'),
  (gen_random_uuid(), 'kanban:acessar', 'Acessar Kanban', 'kanban'),
  (gen_random_uuid(), 'kanban:visualizar', 'Visualizar oportunidades próprias no Kanban', 'kanban'),
  (gen_random_uuid(), 'kanban:visualizar_todas', 'Visualizar todas as oportunidades no Kanban', 'kanban'),
  (gen_random_uuid(), 'kanban:criar', 'Criar oportunidades no Kanban', 'kanban'),
  (gen_random_uuid(), 'kanban:editar', 'Editar e mover oportunidades no Kanban', 'kanban'),
  (gen_random_uuid(), 'kanban:deletar', 'Excluir oportunidades no Kanban', 'kanban'),
  (gen_random_uuid(), 'kanban:fechar', 'Fechar oportunidades como ganhas', 'kanban'),
  (gen_random_uuid(), 'kanban:perder', 'Marcar oportunidades como perdidas', 'kanban'),
  (gen_random_uuid(), 'chat:acessar', 'Acessar Chat da Equipe', 'workspace'),
  (gen_random_uuid(), 'performance:acessar', 'Acessar Ranking de Performance', 'workspace'),
  (gen_random_uuid(), 'performance:visualizar', 'Visualizar dados de performance', 'workspace'),
  (gen_random_uuid(), 'importar_renovacoes:acessar', 'Importar renovações', 'gestao'),
  (gen_random_uuid(), 'aceitar_exclusao:renovacao', 'Aceitar ou recusar solicitações de exclusão de renovação', 'gestao'),
  (gen_random_uuid(), 'gestao_comercial:acessar', 'Acessar Gestão Comercial', 'gestao'),
  (gen_random_uuid(), 'gestao_pessoas:acessar', 'Acessar Gestão de Pessoas', 'gestao'),
  (gen_random_uuid(), 'gestao_crm:acessar', 'Acessar módulo de Gestão CRM', 'gestao'),
  (gen_random_uuid(), 'negocios_corretora:acessar', 'Acessar Negócios da Corretora', 'negocios'),
  (gen_random_uuid(), 'marketing:acessar', 'Acessar área de Marketing (link do portal do segurado)', 'marketing'),
  (gen_random_uuid(), 'auditoria:visualizar', 'Visualizar logs de auditoria', 'auditoria'),
  (gen_random_uuid(), 'auditoria:visualizar_permissoes', 'Visualizar histórico de alterações de permissões', 'auditoria'),
  (gen_random_uuid(), 'auditoria:exportar', 'Exportar logs de auditoria', 'auditoria')
ON CONFLICT ("nome_permissao") DO NOTHING;