/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaticRouteImport } from './routes/_static'
import { Route as PortalRouteImport } from './routes/_portal'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmbedParticlesRouteImport } from './routes/embed/particles'
import { Route as StaticTreinamentosRouteImport } from './routes/_static/treinamentos'
import { Route as StaticTermosRouteImport } from './routes/_static/termos'
import { Route as StaticSobreRouteImport } from './routes/_static/sobre'
import { Route as StaticRoadmapRouteImport } from './routes/_static/roadmap'
import { Route as StaticPrivacidadeRouteImport } from './routes/_static/privacidade'
import { Route as StaticPrecosRouteImport } from './routes/_static/precos'
import { Route as StaticLgpdRouteImport } from './routes/_static/lgpd'
import { Route as StaticIdentidadeVisualRouteImport } from './routes/_static/identidade-visual'
import { Route as StaticFuncionalidadesRouteImport } from './routes/_static/funcionalidades'
import { Route as StaticCookiesRouteImport } from './routes/_static/cookies'
import { Route as StaticContatoRouteImport } from './routes/_static/contato'
import { Route as StaticChangelogRouteImport } from './routes/_static/changelog'
import { Route as StaticCertificadoPreviewRouteImport } from './routes/_static/certificado-preview'
import { Route as StaticBrandingRouteImport } from './routes/_static/branding'
import { Route as AuthResetSenhaRouteImport } from './routes/_auth/reset-senha'
import { Route as AuthRecuperarSenhaRouteImport } from './routes/_auth/recuperar-senha'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppVendedoresRouteImport } from './routes/_app/vendedores'
import { Route as AppUsuariosRouteImport } from './routes/_app/usuarios'
import { Route as AppSemPermissaoRouteImport } from './routes/_app/sem-permissao'
import { Route as AppSeguradorasParceirasRouteImport } from './routes/_app/seguradoras-parceiras'
import { Route as AppRankingRouteImport } from './routes/_app/ranking'
import { Route as AppProdutosRouteImport } from './routes/_app/produtos'
import { Route as AppPerformanceRouteImport } from './routes/_app/performance'
import { Route as AppPerfilRouteImport } from './routes/_app/perfil'
import { Route as AppPainelEquipeRouteImport } from './routes/_app/painel-equipe'
import { Route as AppPainelRouteImport } from './routes/_app/painel'
import { Route as AppNotificacoesRouteImport } from './routes/_app/notificacoes'
import { Route as AppNegociosRouteImport } from './routes/_app/negocios'
import { Route as AppMeuDesempenhoRouteImport } from './routes/_app/meu-desempenho'
import { Route as AppMarketingRouteImport } from './routes/_app/marketing'
import { Route as AppGestaoRouteImport } from './routes/_app/gestao'
import { Route as AppCrmRouteImport } from './routes/_app/crm'
import { Route as AppClientesRouteImport } from './routes/_app/clientes'
import { Route as AppChatRouteImport } from './routes/_app/chat'
import { Route as AppCadastroRouteImport } from './routes/_app/cadastro'
import { Route as AppAgendaRouteImport } from './routes/_app/agenda'
import { Route as StaticDocsIndexRouteImport } from './routes/_static/docs/index'
import { Route as StaticCheckoutIndexRouteImport } from './routes/_static/checkout/index'
import { Route as StaticBlogIndexRouteImport } from './routes/_static/blog/index'
import { Route as AppWorkspace2IndexRouteImport } from './routes/_app/workspace2/index'
import { Route as AppSinistroIndexRouteImport } from './routes/_app/sinistro/index'
import { Route as AppMetricasIndexRouteImport } from './routes/_app/metricas/index'
import { Route as AppImportarRenovacoesIndexRouteImport } from './routes/_app/importar-renovacoes/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as StaticDocsPrimeirosPassosRouteImport } from './routes/_static/docs/primeiros-passos'
import { Route as StaticDocsPerformanceRouteImport } from './routes/_static/docs/performance'
import { Route as StaticDocsOverviewRouteImport } from './routes/_static/docs/overview'
import { Route as StaticDocsMetricasRouteImport } from './routes/_static/docs/metricas'
import { Route as StaticDocsKanbanRouteImport } from './routes/_static/docs/kanban'
import { Route as StaticDocsDashboardRouteImport } from './routes/_static/docs/dashboard'
import { Route as StaticDocsCotacoesRouteImport } from './routes/_static/docs/cotacoes'
import { Route as StaticDocsConfiguracoesRouteImport } from './routes/_static/docs/configuracoes'
import { Route as StaticDocsClientesRouteImport } from './routes/_static/docs/clientes'
import { Route as StaticDocsAgendaRouteImport } from './routes/_static/docs/agenda'
import { Route as StaticCheckoutSucessoRouteImport } from './routes/_static/checkout/sucesso'
import { Route as StaticBlogSlugRouteImport } from './routes/_static/blog/$slug'
import { Route as AppSinistroKanbanRouteImport } from './routes/_app/sinistro/kanban'
import { Route as AppPosVendasCrossSellingRouteImport } from './routes/_app/pos-vendas/cross-selling'
import { Route as AppMetricasRenovacoesRouteImport } from './routes/_app/metricas/renovacoes'
import { Route as AppImportarRenovacoesHistoricoRouteImport } from './routes/_app/importar-renovacoes/historico'
import { Route as AppImportarRenovacoesImportacaoIdRouteImport } from './routes/_app/importar-renovacoes/$importacaoId'
import { Route as AppEquipeIdRouteImport } from './routes/_app/equipe/$id'
import { Route as AppDashboardKanbanRouteImport } from './routes/_app/dashboard/kanban'
import { Route as AppConfiguracoesCorretoraRouteImport } from './routes/_app/configuracoes/corretora'
import { Route as AppConfiguracoesComissoesRouteImport } from './routes/_app/configuracoes/comissoes'
import { Route as AppConfiguracoesCargosRouteImport } from './routes/_app/configuracoes/cargos'
import { Route as AdminAdminTenantsRouteImport } from './routes/_admin/admin/tenants'
import { Route as AdminAdminSubscriptionsRouteImport } from './routes/_admin/admin/subscriptions'
import { Route as AdminAdminRoadmapRouteImport } from './routes/_admin/admin/roadmap'
import { Route as AdminAdminPricingRouteImport } from './routes/_admin/admin/pricing'
import { Route as AdminAdminPerfilRouteImport } from './routes/_admin/admin/perfil'
import { Route as AdminAdminLoginRouteImport } from './routes/_admin/admin/login'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin/admin/dashboard'
import { Route as AdminAdminChangelogsRouteImport } from './routes/_admin/admin/changelogs'
import { Route as AdminAdminBlogRouteImport } from './routes/_admin/admin/blog'
import { Route as AdminAdminBackupsRouteImport } from './routes/_admin/admin/backups'
import { Route as AdminAdminAuditLogsRouteImport } from './routes/_admin/admin/audit-logs'
import { Route as PortalPortalSubdominioIndexRouteImport } from './routes/_portal/portal/$subdominio/index'
import { Route as AdminAdminTreinamentosIndexRouteImport } from './routes/_admin/admin/treinamentos/index'
import { Route as PortalPortalSubdominioVencimentosRouteImport } from './routes/_portal/portal/$subdominio/vencimentos'
import { Route as PortalPortalSubdominioProdutosRouteImport } from './routes/_portal/portal/$subdominio/produtos'
import { Route as PortalPortalSubdominioPerfilRouteImport } from './routes/_portal/portal/$subdominio/perfil'
import { Route as PortalPortalSubdominioLoginRouteImport } from './routes/_portal/portal/$subdominio/login'
import { Route as AppMetricasVendedorVendedorIdRouteImport } from './routes/_app/metricas/vendedor/$vendedorId'
import { Route as AdminAdminTreinamentosCursoIdRouteImport } from './routes/_admin/admin/treinamentos/$cursoId'
import { Route as PortalPortalSubdominioApolicesIndexRouteImport } from './routes/_portal/portal/$subdominio/apolices/index'
import { Route as PortalPortalSubdominioApolicesIdRouteImport } from './routes/_portal/portal/$subdominio/apolices/$id'

const StaticRoute = StaticRouteImport.update({
  id: '/_static',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedParticlesRoute = EmbedParticlesRouteImport.update({
  id: '/embed/particles',
  path: '/embed/particles',
  getParentRoute: () => rootRouteImport,
} as any)
const StaticTreinamentosRoute = StaticTreinamentosRouteImport.update({
  id: '/treinamentos',
  path: '/treinamentos',
  getParentRoute: () => StaticRoute,
} as any)
const StaticTermosRoute = StaticTermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => StaticRoute,
} as any)
const StaticSobreRoute = StaticSobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => StaticRoute,
} as any)
const StaticRoadmapRoute = StaticRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => StaticRoute,
} as any)
const StaticPrivacidadeRoute = StaticPrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => StaticRoute,
} as any)
const StaticPrecosRoute = StaticPrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => StaticRoute,
} as any)
const StaticLgpdRoute = StaticLgpdRouteImport.update({
  id: '/lgpd',
  path: '/lgpd',
  getParentRoute: () => StaticRoute,
} as any)
const StaticIdentidadeVisualRoute = StaticIdentidadeVisualRouteImport.update({
  id: '/identidade-visual',
  path: '/identidade-visual',
  getParentRoute: () => StaticRoute,
} as any)
const StaticFuncionalidadesRoute = StaticFuncionalidadesRouteImport.update({
  id: '/funcionalidades',
  path: '/funcionalidades',
  getParentRoute: () => StaticRoute,
} as any)
const StaticCookiesRoute = StaticCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => StaticRoute,
} as any)
const StaticContatoRoute = StaticContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => StaticRoute,
} as any)
const StaticChangelogRoute = StaticChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => StaticRoute,
} as any)
const StaticCertificadoPreviewRoute =
  StaticCertificadoPreviewRouteImport.update({
    id: '/certificado-preview',
    path: '/certificado-preview',
    getParentRoute: () => StaticRoute,
  } as any)
const StaticBrandingRoute = StaticBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => StaticRoute,
} as any)
const AuthResetSenhaRoute = AuthResetSenhaRouteImport.update({
  id: '/reset-senha',
  path: '/reset-senha',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRecuperarSenhaRoute = AuthRecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppVendedoresRoute = AppVendedoresRouteImport.update({
  id: '/vendedores',
  path: '/vendedores',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppSemPermissaoRoute = AppSemPermissaoRouteImport.update({
  id: '/sem-permissao',
  path: '/sem-permissao',
  getParentRoute: () => AppRoute,
} as any)
const AppSeguradorasParceirasRoute = AppSeguradorasParceirasRouteImport.update({
  id: '/seguradoras-parceiras',
  path: '/seguradoras-parceiras',
  getParentRoute: () => AppRoute,
} as any)
const AppRankingRoute = AppRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutosRoute = AppProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppPainelEquipeRoute = AppPainelEquipeRouteImport.update({
  id: '/painel-equipe',
  path: '/painel-equipe',
  getParentRoute: () => AppRoute,
} as any)
const AppPainelRoute = AppPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificacoesRoute = AppNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppNegociosRoute = AppNegociosRouteImport.update({
  id: '/negocios',
  path: '/negocios',
  getParentRoute: () => AppRoute,
} as any)
const AppMeuDesempenhoRoute = AppMeuDesempenhoRouteImport.update({
  id: '/meu-desempenho',
  path: '/meu-desempenho',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingRoute = AppMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AppRoute,
} as any)
const AppGestaoRoute = AppGestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppCadastroRoute = AppCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const StaticDocsIndexRoute = StaticDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => StaticRoute,
} as any)
const StaticCheckoutIndexRoute = StaticCheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => StaticRoute,
} as any)
const StaticBlogIndexRoute = StaticBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => StaticRoute,
} as any)
const AppWorkspace2IndexRoute = AppWorkspace2IndexRouteImport.update({
  id: '/workspace2/',
  path: '/workspace2/',
  getParentRoute: () => AppRoute,
} as any)
const AppSinistroIndexRoute = AppSinistroIndexRouteImport.update({
  id: '/sinistro/',
  path: '/sinistro/',
  getParentRoute: () => AppRoute,
} as any)
const AppMetricasIndexRoute = AppMetricasIndexRouteImport.update({
  id: '/metricas/',
  path: '/metricas/',
  getParentRoute: () => AppRoute,
} as any)
const AppImportarRenovacoesIndexRoute =
  AppImportarRenovacoesIndexRouteImport.update({
    id: '/importar-renovacoes/',
    path: '/importar-renovacoes/',
    getParentRoute: () => AppRoute,
  } as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRoute,
} as any)
const StaticDocsPrimeirosPassosRoute =
  StaticDocsPrimeirosPassosRouteImport.update({
    id: '/docs/primeiros-passos',
    path: '/docs/primeiros-passos',
    getParentRoute: () => StaticRoute,
  } as any)
const StaticDocsPerformanceRoute = StaticDocsPerformanceRouteImport.update({
  id: '/docs/performance',
  path: '/docs/performance',
  getParentRoute: () => StaticRoute,
} as any)
const StaticDocsOverviewRoute = StaticDocsOverviewRouteImport.update({
  id: '/docs/overview',
  path: '/docs/overview',
  getParentRoute: () => StaticRoute,
} as any)
const StaticDocsMetricasRoute = StaticDocsMetricasRouteImport.update({
  id: '/docs/metricas',
  path: '/docs/metricas',
  getParentRoute: () => StaticRoute,
} as any)
const StaticDocsKanbanRoute = StaticDocsKanbanRouteImport.update({
  id: '/docs/kanban',
  path: '/docs/kanban',
  getParentRoute: () => StaticRoute,
} as any)
const StaticDocsDashboardRoute = StaticDocsDashboardRouteImport.update({
  id: '/docs/dashboard',
  path: '/docs/dashboard',
  getParentRoute: () => StaticRoute,
} as any)
const StaticDocsCotacoesRoute = StaticDocsCotacoesRouteImport.update({
  id: '/docs/cotacoes',
  path: '/docs/cotacoes',
  getParentRoute: () => StaticRoute,
} as any)
const StaticDocsConfiguracoesRoute = StaticDocsConfiguracoesRouteImport.update({
  id: '/docs/configuracoes',
  path: '/docs/configuracoes',
  getParentRoute: () => StaticRoute,
} as any)
const StaticDocsClientesRoute = StaticDocsClientesRouteImport.update({
  id: '/docs/clientes',
  path: '/docs/clientes',
  getParentRoute: () => StaticRoute,
} as any)
const StaticDocsAgendaRoute = StaticDocsAgendaRouteImport.update({
  id: '/docs/agenda',
  path: '/docs/agenda',
  getParentRoute: () => StaticRoute,
} as any)
const StaticCheckoutSucessoRoute = StaticCheckoutSucessoRouteImport.update({
  id: '/checkout/sucesso',
  path: '/checkout/sucesso',
  getParentRoute: () => StaticRoute,
} as any)
const StaticBlogSlugRoute = StaticBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => StaticRoute,
} as any)
const AppSinistroKanbanRoute = AppSinistroKanbanRouteImport.update({
  id: '/sinistro/kanban',
  path: '/sinistro/kanban',
  getParentRoute: () => AppRoute,
} as any)
const AppPosVendasCrossSellingRoute =
  AppPosVendasCrossSellingRouteImport.update({
    id: '/pos-vendas/cross-selling',
    path: '/pos-vendas/cross-selling',
    getParentRoute: () => AppRoute,
  } as any)
const AppMetricasRenovacoesRoute = AppMetricasRenovacoesRouteImport.update({
  id: '/metricas/renovacoes',
  path: '/metricas/renovacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppImportarRenovacoesHistoricoRoute =
  AppImportarRenovacoesHistoricoRouteImport.update({
    id: '/importar-renovacoes/historico',
    path: '/importar-renovacoes/historico',
    getParentRoute: () => AppRoute,
  } as any)
const AppImportarRenovacoesImportacaoIdRoute =
  AppImportarRenovacoesImportacaoIdRouteImport.update({
    id: '/importar-renovacoes/$importacaoId',
    path: '/importar-renovacoes/$importacaoId',
    getParentRoute: () => AppRoute,
  } as any)
const AppEquipeIdRoute = AppEquipeIdRouteImport.update({
  id: '/equipe/$id',
  path: '/equipe/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardKanbanRoute = AppDashboardKanbanRouteImport.update({
  id: '/dashboard/kanban',
  path: '/dashboard/kanban',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesCorretoraRoute =
  AppConfiguracoesCorretoraRouteImport.update({
    id: '/configuracoes/corretora',
    path: '/configuracoes/corretora',
    getParentRoute: () => AppRoute,
  } as any)
const AppConfiguracoesComissoesRoute =
  AppConfiguracoesComissoesRouteImport.update({
    id: '/configuracoes/comissoes',
    path: '/configuracoes/comissoes',
    getParentRoute: () => AppRoute,
  } as any)
const AppConfiguracoesCargosRoute = AppConfiguracoesCargosRouteImport.update({
  id: '/configuracoes/cargos',
  path: '/configuracoes/cargos',
  getParentRoute: () => AppRoute,
} as any)
const AdminAdminTenantsRoute = AdminAdminTenantsRouteImport.update({
  id: '/admin/tenants',
  path: '/admin/tenants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSubscriptionsRoute = AdminAdminSubscriptionsRouteImport.update({
  id: '/admin/subscriptions',
  path: '/admin/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminRoadmapRoute = AdminAdminRoadmapRouteImport.update({
  id: '/admin/roadmap',
  path: '/admin/roadmap',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPricingRoute = AdminAdminPricingRouteImport.update({
  id: '/admin/pricing',
  path: '/admin/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPerfilRoute = AdminAdminPerfilRouteImport.update({
  id: '/admin/perfil',
  path: '/admin/perfil',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminLoginRoute = AdminAdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminChangelogsRoute = AdminAdminChangelogsRouteImport.update({
  id: '/admin/changelogs',
  path: '/admin/changelogs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminBlogRoute = AdminAdminBlogRouteImport.update({
  id: '/admin/blog',
  path: '/admin/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminBackupsRoute = AdminAdminBackupsRouteImport.update({
  id: '/admin/backups',
  path: '/admin/backups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAuditLogsRoute = AdminAdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const PortalPortalSubdominioIndexRoute =
  PortalPortalSubdominioIndexRouteImport.update({
    id: '/portal/$subdominio/',
    path: '/portal/$subdominio/',
    getParentRoute: () => PortalRoute,
  } as any)
const AdminAdminTreinamentosIndexRoute =
  AdminAdminTreinamentosIndexRouteImport.update({
    id: '/admin/treinamentos/',
    path: '/admin/treinamentos/',
    getParentRoute: () => AdminRoute,
  } as any)
const PortalPortalSubdominioVencimentosRoute =
  PortalPortalSubdominioVencimentosRouteImport.update({
    id: '/portal/$subdominio/vencimentos',
    path: '/portal/$subdominio/vencimentos',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalPortalSubdominioProdutosRoute =
  PortalPortalSubdominioProdutosRouteImport.update({
    id: '/portal/$subdominio/produtos',
    path: '/portal/$subdominio/produtos',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalPortalSubdominioPerfilRoute =
  PortalPortalSubdominioPerfilRouteImport.update({
    id: '/portal/$subdominio/perfil',
    path: '/portal/$subdominio/perfil',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalPortalSubdominioLoginRoute =
  PortalPortalSubdominioLoginRouteImport.update({
    id: '/portal/$subdominio/login',
    path: '/portal/$subdominio/login',
    getParentRoute: () => PortalRoute,
  } as any)
const AppMetricasVendedorVendedorIdRoute =
  AppMetricasVendedorVendedorIdRouteImport.update({
    id: '/metricas/vendedor/$vendedorId',
    path: '/metricas/vendedor/$vendedorId',
    getParentRoute: () => AppRoute,
  } as any)
const AdminAdminTreinamentosCursoIdRoute =
  AdminAdminTreinamentosCursoIdRouteImport.update({
    id: '/admin/treinamentos/$cursoId',
    path: '/admin/treinamentos/$cursoId',
    getParentRoute: () => AdminRoute,
  } as any)
const PortalPortalSubdominioApolicesIndexRoute =
  PortalPortalSubdominioApolicesIndexRouteImport.update({
    id: '/portal/$subdominio/apolices/',
    path: '/portal/$subdominio/apolices/',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalPortalSubdominioApolicesIdRoute =
  PortalPortalSubdominioApolicesIdRouteImport.update({
    id: '/portal/$subdominio/apolices/$id',
    path: '/portal/$subdominio/apolices/$id',
    getParentRoute: () => PortalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/agenda': typeof AppAgendaRoute
  '/cadastro': typeof AppCadastroRoute
  '/chat': typeof AppChatRoute
  '/clientes': typeof AppClientesRoute
  '/crm': typeof AppCrmRoute
  '/gestao': typeof AppGestaoRoute
  '/marketing': typeof AppMarketingRoute
  '/meu-desempenho': typeof AppMeuDesempenhoRoute
  '/negocios': typeof AppNegociosRoute
  '/notificacoes': typeof AppNotificacoesRoute
  '/painel': typeof AppPainelRoute
  '/painel-equipe': typeof AppPainelEquipeRoute
  '/perfil': typeof AppPerfilRoute
  '/performance': typeof AppPerformanceRoute
  '/produtos': typeof AppProdutosRoute
  '/ranking': typeof AppRankingRoute
  '/seguradoras-parceiras': typeof AppSeguradorasParceirasRoute
  '/sem-permissao': typeof AppSemPermissaoRoute
  '/usuarios': typeof AppUsuariosRoute
  '/vendedores': typeof AppVendedoresRoute
  '/login': typeof AuthLoginRoute
  '/recuperar-senha': typeof AuthRecuperarSenhaRoute
  '/reset-senha': typeof AuthResetSenhaRoute
  '/branding': typeof StaticBrandingRoute
  '/certificado-preview': typeof StaticCertificadoPreviewRoute
  '/changelog': typeof StaticChangelogRoute
  '/contato': typeof StaticContatoRoute
  '/cookies': typeof StaticCookiesRoute
  '/funcionalidades': typeof StaticFuncionalidadesRoute
  '/identidade-visual': typeof StaticIdentidadeVisualRoute
  '/lgpd': typeof StaticLgpdRoute
  '/precos': typeof StaticPrecosRoute
  '/privacidade': typeof StaticPrivacidadeRoute
  '/roadmap': typeof StaticRoadmapRoute
  '/sobre': typeof StaticSobreRoute
  '/termos': typeof StaticTermosRoute
  '/treinamentos': typeof StaticTreinamentosRoute
  '/embed/particles': typeof EmbedParticlesRoute
  '/admin/audit-logs': typeof AdminAdminAuditLogsRoute
  '/admin/backups': typeof AdminAdminBackupsRoute
  '/admin/blog': typeof AdminAdminBlogRoute
  '/admin/changelogs': typeof AdminAdminChangelogsRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/login': typeof AdminAdminLoginRoute
  '/admin/perfil': typeof AdminAdminPerfilRoute
  '/admin/pricing': typeof AdminAdminPricingRoute
  '/admin/roadmap': typeof AdminAdminRoadmapRoute
  '/admin/subscriptions': typeof AdminAdminSubscriptionsRoute
  '/admin/tenants': typeof AdminAdminTenantsRoute
  '/configuracoes/cargos': typeof AppConfiguracoesCargosRoute
  '/configuracoes/comissoes': typeof AppConfiguracoesComissoesRoute
  '/configuracoes/corretora': typeof AppConfiguracoesCorretoraRoute
  '/dashboard/kanban': typeof AppDashboardKanbanRoute
  '/equipe/$id': typeof AppEquipeIdRoute
  '/importar-renovacoes/$importacaoId': typeof AppImportarRenovacoesImportacaoIdRoute
  '/importar-renovacoes/historico': typeof AppImportarRenovacoesHistoricoRoute
  '/metricas/renovacoes': typeof AppMetricasRenovacoesRoute
  '/pos-vendas/cross-selling': typeof AppPosVendasCrossSellingRoute
  '/sinistro/kanban': typeof AppSinistroKanbanRoute
  '/blog/$slug': typeof StaticBlogSlugRoute
  '/checkout/sucesso': typeof StaticCheckoutSucessoRoute
  '/docs/agenda': typeof StaticDocsAgendaRoute
  '/docs/clientes': typeof StaticDocsClientesRoute
  '/docs/configuracoes': typeof StaticDocsConfiguracoesRoute
  '/docs/cotacoes': typeof StaticDocsCotacoesRoute
  '/docs/dashboard': typeof StaticDocsDashboardRoute
  '/docs/kanban': typeof StaticDocsKanbanRoute
  '/docs/metricas': typeof StaticDocsMetricasRoute
  '/docs/overview': typeof StaticDocsOverviewRoute
  '/docs/performance': typeof StaticDocsPerformanceRoute
  '/docs/primeiros-passos': typeof StaticDocsPrimeirosPassosRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/importar-renovacoes/': typeof AppImportarRenovacoesIndexRoute
  '/metricas/': typeof AppMetricasIndexRoute
  '/sinistro/': typeof AppSinistroIndexRoute
  '/workspace2/': typeof AppWorkspace2IndexRoute
  '/blog/': typeof StaticBlogIndexRoute
  '/checkout/': typeof StaticCheckoutIndexRoute
  '/docs/': typeof StaticDocsIndexRoute
  '/admin/treinamentos/$cursoId': typeof AdminAdminTreinamentosCursoIdRoute
  '/metricas/vendedor/$vendedorId': typeof AppMetricasVendedorVendedorIdRoute
  '/portal/$subdominio/login': typeof PortalPortalSubdominioLoginRoute
  '/portal/$subdominio/perfil': typeof PortalPortalSubdominioPerfilRoute
  '/portal/$subdominio/produtos': typeof PortalPortalSubdominioProdutosRoute
  '/portal/$subdominio/vencimentos': typeof PortalPortalSubdominioVencimentosRoute
  '/admin/treinamentos/': typeof AdminAdminTreinamentosIndexRoute
  '/portal/$subdominio/': typeof PortalPortalSubdominioIndexRoute
  '/portal/$subdominio/apolices/$id': typeof PortalPortalSubdominioApolicesIdRoute
  '/portal/$subdominio/apolices/': typeof PortalPortalSubdominioApolicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/agenda': typeof AppAgendaRoute
  '/cadastro': typeof AppCadastroRoute
  '/chat': typeof AppChatRoute
  '/clientes': typeof AppClientesRoute
  '/crm': typeof AppCrmRoute
  '/gestao': typeof AppGestaoRoute
  '/marketing': typeof AppMarketingRoute
  '/meu-desempenho': typeof AppMeuDesempenhoRoute
  '/negocios': typeof AppNegociosRoute
  '/notificacoes': typeof AppNotificacoesRoute
  '/painel': typeof AppPainelRoute
  '/painel-equipe': typeof AppPainelEquipeRoute
  '/perfil': typeof AppPerfilRoute
  '/performance': typeof AppPerformanceRoute
  '/produtos': typeof AppProdutosRoute
  '/ranking': typeof AppRankingRoute
  '/seguradoras-parceiras': typeof AppSeguradorasParceirasRoute
  '/sem-permissao': typeof AppSemPermissaoRoute
  '/usuarios': typeof AppUsuariosRoute
  '/vendedores': typeof AppVendedoresRoute
  '/login': typeof AuthLoginRoute
  '/recuperar-senha': typeof AuthRecuperarSenhaRoute
  '/reset-senha': typeof AuthResetSenhaRoute
  '/branding': typeof StaticBrandingRoute
  '/certificado-preview': typeof StaticCertificadoPreviewRoute
  '/changelog': typeof StaticChangelogRoute
  '/contato': typeof StaticContatoRoute
  '/cookies': typeof StaticCookiesRoute
  '/funcionalidades': typeof StaticFuncionalidadesRoute
  '/identidade-visual': typeof StaticIdentidadeVisualRoute
  '/lgpd': typeof StaticLgpdRoute
  '/precos': typeof StaticPrecosRoute
  '/privacidade': typeof StaticPrivacidadeRoute
  '/roadmap': typeof StaticRoadmapRoute
  '/sobre': typeof StaticSobreRoute
  '/termos': typeof StaticTermosRoute
  '/treinamentos': typeof StaticTreinamentosRoute
  '/embed/particles': typeof EmbedParticlesRoute
  '/admin/audit-logs': typeof AdminAdminAuditLogsRoute
  '/admin/backups': typeof AdminAdminBackupsRoute
  '/admin/blog': typeof AdminAdminBlogRoute
  '/admin/changelogs': typeof AdminAdminChangelogsRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/login': typeof AdminAdminLoginRoute
  '/admin/perfil': typeof AdminAdminPerfilRoute
  '/admin/pricing': typeof AdminAdminPricingRoute
  '/admin/roadmap': typeof AdminAdminRoadmapRoute
  '/admin/subscriptions': typeof AdminAdminSubscriptionsRoute
  '/admin/tenants': typeof AdminAdminTenantsRoute
  '/configuracoes/cargos': typeof AppConfiguracoesCargosRoute
  '/configuracoes/comissoes': typeof AppConfiguracoesComissoesRoute
  '/configuracoes/corretora': typeof AppConfiguracoesCorretoraRoute
  '/dashboard/kanban': typeof AppDashboardKanbanRoute
  '/equipe/$id': typeof AppEquipeIdRoute
  '/importar-renovacoes/$importacaoId': typeof AppImportarRenovacoesImportacaoIdRoute
  '/importar-renovacoes/historico': typeof AppImportarRenovacoesHistoricoRoute
  '/metricas/renovacoes': typeof AppMetricasRenovacoesRoute
  '/pos-vendas/cross-selling': typeof AppPosVendasCrossSellingRoute
  '/sinistro/kanban': typeof AppSinistroKanbanRoute
  '/blog/$slug': typeof StaticBlogSlugRoute
  '/checkout/sucesso': typeof StaticCheckoutSucessoRoute
  '/docs/agenda': typeof StaticDocsAgendaRoute
  '/docs/clientes': typeof StaticDocsClientesRoute
  '/docs/configuracoes': typeof StaticDocsConfiguracoesRoute
  '/docs/cotacoes': typeof StaticDocsCotacoesRoute
  '/docs/dashboard': typeof StaticDocsDashboardRoute
  '/docs/kanban': typeof StaticDocsKanbanRoute
  '/docs/metricas': typeof StaticDocsMetricasRoute
  '/docs/overview': typeof StaticDocsOverviewRoute
  '/docs/performance': typeof StaticDocsPerformanceRoute
  '/docs/primeiros-passos': typeof StaticDocsPrimeirosPassosRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/importar-renovacoes': typeof AppImportarRenovacoesIndexRoute
  '/metricas': typeof AppMetricasIndexRoute
  '/sinistro': typeof AppSinistroIndexRoute
  '/workspace2': typeof AppWorkspace2IndexRoute
  '/blog': typeof StaticBlogIndexRoute
  '/checkout': typeof StaticCheckoutIndexRoute
  '/docs': typeof StaticDocsIndexRoute
  '/admin/treinamentos/$cursoId': typeof AdminAdminTreinamentosCursoIdRoute
  '/metricas/vendedor/$vendedorId': typeof AppMetricasVendedorVendedorIdRoute
  '/portal/$subdominio/login': typeof PortalPortalSubdominioLoginRoute
  '/portal/$subdominio/perfil': typeof PortalPortalSubdominioPerfilRoute
  '/portal/$subdominio/produtos': typeof PortalPortalSubdominioProdutosRoute
  '/portal/$subdominio/vencimentos': typeof PortalPortalSubdominioVencimentosRoute
  '/admin/treinamentos': typeof AdminAdminTreinamentosIndexRoute
  '/portal/$subdominio': typeof PortalPortalSubdominioIndexRoute
  '/portal/$subdominio/apolices/$id': typeof PortalPortalSubdominioApolicesIdRoute
  '/portal/$subdominio/apolices': typeof PortalPortalSubdominioApolicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/_admin': typeof AdminRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_portal': typeof PortalRouteWithChildren
  '/_static': typeof StaticRouteWithChildren
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/cadastro': typeof AppCadastroRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/clientes': typeof AppClientesRoute
  '/_app/crm': typeof AppCrmRoute
  '/_app/gestao': typeof AppGestaoRoute
  '/_app/marketing': typeof AppMarketingRoute
  '/_app/meu-desempenho': typeof AppMeuDesempenhoRoute
  '/_app/negocios': typeof AppNegociosRoute
  '/_app/notificacoes': typeof AppNotificacoesRoute
  '/_app/painel': typeof AppPainelRoute
  '/_app/painel-equipe': typeof AppPainelEquipeRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/performance': typeof AppPerformanceRoute
  '/_app/produtos': typeof AppProdutosRoute
  '/_app/ranking': typeof AppRankingRoute
  '/_app/seguradoras-parceiras': typeof AppSeguradorasParceirasRoute
  '/_app/sem-permissao': typeof AppSemPermissaoRoute
  '/_app/usuarios': typeof AppUsuariosRoute
  '/_app/vendedores': typeof AppVendedoresRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/recuperar-senha': typeof AuthRecuperarSenhaRoute
  '/_auth/reset-senha': typeof AuthResetSenhaRoute
  '/_static/branding': typeof StaticBrandingRoute
  '/_static/certificado-preview': typeof StaticCertificadoPreviewRoute
  '/_static/changelog': typeof StaticChangelogRoute
  '/_static/contato': typeof StaticContatoRoute
  '/_static/cookies': typeof StaticCookiesRoute
  '/_static/funcionalidades': typeof StaticFuncionalidadesRoute
  '/_static/identidade-visual': typeof StaticIdentidadeVisualRoute
  '/_static/lgpd': typeof StaticLgpdRoute
  '/_static/precos': typeof StaticPrecosRoute
  '/_static/privacidade': typeof StaticPrivacidadeRoute
  '/_static/roadmap': typeof StaticRoadmapRoute
  '/_static/sobre': typeof StaticSobreRoute
  '/_static/termos': typeof StaticTermosRoute
  '/_static/treinamentos': typeof StaticTreinamentosRoute
  '/embed/particles': typeof EmbedParticlesRoute
  '/_admin/admin/audit-logs': typeof AdminAdminAuditLogsRoute
  '/_admin/admin/backups': typeof AdminAdminBackupsRoute
  '/_admin/admin/blog': typeof AdminAdminBlogRoute
  '/_admin/admin/changelogs': typeof AdminAdminChangelogsRoute
  '/_admin/admin/dashboard': typeof AdminAdminDashboardRoute
  '/_admin/admin/login': typeof AdminAdminLoginRoute
  '/_admin/admin/perfil': typeof AdminAdminPerfilRoute
  '/_admin/admin/pricing': typeof AdminAdminPricingRoute
  '/_admin/admin/roadmap': typeof AdminAdminRoadmapRoute
  '/_admin/admin/subscriptions': typeof AdminAdminSubscriptionsRoute
  '/_admin/admin/tenants': typeof AdminAdminTenantsRoute
  '/_app/configuracoes/cargos': typeof AppConfiguracoesCargosRoute
  '/_app/configuracoes/comissoes': typeof AppConfiguracoesComissoesRoute
  '/_app/configuracoes/corretora': typeof AppConfiguracoesCorretoraRoute
  '/_app/dashboard/kanban': typeof AppDashboardKanbanRoute
  '/_app/equipe/$id': typeof AppEquipeIdRoute
  '/_app/importar-renovacoes/$importacaoId': typeof AppImportarRenovacoesImportacaoIdRoute
  '/_app/importar-renovacoes/historico': typeof AppImportarRenovacoesHistoricoRoute
  '/_app/metricas/renovacoes': typeof AppMetricasRenovacoesRoute
  '/_app/pos-vendas/cross-selling': typeof AppPosVendasCrossSellingRoute
  '/_app/sinistro/kanban': typeof AppSinistroKanbanRoute
  '/_static/blog/$slug': typeof StaticBlogSlugRoute
  '/_static/checkout/sucesso': typeof StaticCheckoutSucessoRoute
  '/_static/docs/agenda': typeof StaticDocsAgendaRoute
  '/_static/docs/clientes': typeof StaticDocsClientesRoute
  '/_static/docs/configuracoes': typeof StaticDocsConfiguracoesRoute
  '/_static/docs/cotacoes': typeof StaticDocsCotacoesRoute
  '/_static/docs/dashboard': typeof StaticDocsDashboardRoute
  '/_static/docs/kanban': typeof StaticDocsKanbanRoute
  '/_static/docs/metricas': typeof StaticDocsMetricasRoute
  '/_static/docs/overview': typeof StaticDocsOverviewRoute
  '/_static/docs/performance': typeof StaticDocsPerformanceRoute
  '/_static/docs/primeiros-passos': typeof StaticDocsPrimeirosPassosRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/importar-renovacoes/': typeof AppImportarRenovacoesIndexRoute
  '/_app/metricas/': typeof AppMetricasIndexRoute
  '/_app/sinistro/': typeof AppSinistroIndexRoute
  '/_app/workspace2/': typeof AppWorkspace2IndexRoute
  '/_static/blog/': typeof StaticBlogIndexRoute
  '/_static/checkout/': typeof StaticCheckoutIndexRoute
  '/_static/docs/': typeof StaticDocsIndexRoute
  '/_admin/admin/treinamentos/$cursoId': typeof AdminAdminTreinamentosCursoIdRoute
  '/_app/metricas/vendedor/$vendedorId': typeof AppMetricasVendedorVendedorIdRoute
  '/_portal/portal/$subdominio/login': typeof PortalPortalSubdominioLoginRoute
  '/_portal/portal/$subdominio/perfil': typeof PortalPortalSubdominioPerfilRoute
  '/_portal/portal/$subdominio/produtos': typeof PortalPortalSubdominioProdutosRoute
  '/_portal/portal/$subdominio/vencimentos': typeof PortalPortalSubdominioVencimentosRoute
  '/_admin/admin/treinamentos/': typeof AdminAdminTreinamentosIndexRoute
  '/_portal/portal/$subdominio/': typeof PortalPortalSubdominioIndexRoute
  '/_portal/portal/$subdominio/apolices/$id': typeof PortalPortalSubdominioApolicesIdRoute
  '/_portal/portal/$subdominio/apolices/': typeof PortalPortalSubdominioApolicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/agenda'
    | '/cadastro'
    | '/chat'
    | '/clientes'
    | '/crm'
    | '/gestao'
    | '/marketing'
    | '/meu-desempenho'
    | '/negocios'
    | '/notificacoes'
    | '/painel'
    | '/painel-equipe'
    | '/perfil'
    | '/performance'
    | '/produtos'
    | '/ranking'
    | '/seguradoras-parceiras'
    | '/sem-permissao'
    | '/usuarios'
    | '/vendedores'
    | '/login'
    | '/recuperar-senha'
    | '/reset-senha'
    | '/branding'
    | '/certificado-preview'
    | '/changelog'
    | '/contato'
    | '/cookies'
    | '/funcionalidades'
    | '/identidade-visual'
    | '/lgpd'
    | '/precos'
    | '/privacidade'
    | '/roadmap'
    | '/sobre'
    | '/termos'
    | '/treinamentos'
    | '/embed/particles'
    | '/admin/audit-logs'
    | '/admin/backups'
    | '/admin/blog'
    | '/admin/changelogs'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/perfil'
    | '/admin/pricing'
    | '/admin/roadmap'
    | '/admin/subscriptions'
    | '/admin/tenants'
    | '/configuracoes/cargos'
    | '/configuracoes/comissoes'
    | '/configuracoes/corretora'
    | '/dashboard/kanban'
    | '/equipe/$id'
    | '/importar-renovacoes/$importacaoId'
    | '/importar-renovacoes/historico'
    | '/metricas/renovacoes'
    | '/pos-vendas/cross-selling'
    | '/sinistro/kanban'
    | '/blog/$slug'
    | '/checkout/sucesso'
    | '/docs/agenda'
    | '/docs/clientes'
    | '/docs/configuracoes'
    | '/docs/cotacoes'
    | '/docs/dashboard'
    | '/docs/kanban'
    | '/docs/metricas'
    | '/docs/overview'
    | '/docs/performance'
    | '/docs/primeiros-passos'
    | '/dashboard/'
    | '/importar-renovacoes/'
    | '/metricas/'
    | '/sinistro/'
    | '/workspace2/'
    | '/blog/'
    | '/checkout/'
    | '/docs/'
    | '/admin/treinamentos/$cursoId'
    | '/metricas/vendedor/$vendedorId'
    | '/portal/$subdominio/login'
    | '/portal/$subdominio/perfil'
    | '/portal/$subdominio/produtos'
    | '/portal/$subdominio/vencimentos'
    | '/admin/treinamentos/'
    | '/portal/$subdominio/'
    | '/portal/$subdominio/apolices/$id'
    | '/portal/$subdominio/apolices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/agenda'
    | '/cadastro'
    | '/chat'
    | '/clientes'
    | '/crm'
    | '/gestao'
    | '/marketing'
    | '/meu-desempenho'
    | '/negocios'
    | '/notificacoes'
    | '/painel'
    | '/painel-equipe'
    | '/perfil'
    | '/performance'
    | '/produtos'
    | '/ranking'
    | '/seguradoras-parceiras'
    | '/sem-permissao'
    | '/usuarios'
    | '/vendedores'
    | '/login'
    | '/recuperar-senha'
    | '/reset-senha'
    | '/branding'
    | '/certificado-preview'
    | '/changelog'
    | '/contato'
    | '/cookies'
    | '/funcionalidades'
    | '/identidade-visual'
    | '/lgpd'
    | '/precos'
    | '/privacidade'
    | '/roadmap'
    | '/sobre'
    | '/termos'
    | '/treinamentos'
    | '/embed/particles'
    | '/admin/audit-logs'
    | '/admin/backups'
    | '/admin/blog'
    | '/admin/changelogs'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/perfil'
    | '/admin/pricing'
    | '/admin/roadmap'
    | '/admin/subscriptions'
    | '/admin/tenants'
    | '/configuracoes/cargos'
    | '/configuracoes/comissoes'
    | '/configuracoes/corretora'
    | '/dashboard/kanban'
    | '/equipe/$id'
    | '/importar-renovacoes/$importacaoId'
    | '/importar-renovacoes/historico'
    | '/metricas/renovacoes'
    | '/pos-vendas/cross-selling'
    | '/sinistro/kanban'
    | '/blog/$slug'
    | '/checkout/sucesso'
    | '/docs/agenda'
    | '/docs/clientes'
    | '/docs/configuracoes'
    | '/docs/cotacoes'
    | '/docs/dashboard'
    | '/docs/kanban'
    | '/docs/metricas'
    | '/docs/overview'
    | '/docs/performance'
    | '/docs/primeiros-passos'
    | '/dashboard'
    | '/importar-renovacoes'
    | '/metricas'
    | '/sinistro'
    | '/workspace2'
    | '/blog'
    | '/checkout'
    | '/docs'
    | '/admin/treinamentos/$cursoId'
    | '/metricas/vendedor/$vendedorId'
    | '/portal/$subdominio/login'
    | '/portal/$subdominio/perfil'
    | '/portal/$subdominio/produtos'
    | '/portal/$subdominio/vencimentos'
    | '/admin/treinamentos'
    | '/portal/$subdominio'
    | '/portal/$subdominio/apolices/$id'
    | '/portal/$subdominio/apolices'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/_admin'
    | '/_app'
    | '/_auth'
    | '/_portal'
    | '/_static'
    | '/_app/agenda'
    | '/_app/cadastro'
    | '/_app/chat'
    | '/_app/clientes'
    | '/_app/crm'
    | '/_app/gestao'
    | '/_app/marketing'
    | '/_app/meu-desempenho'
    | '/_app/negocios'
    | '/_app/notificacoes'
    | '/_app/painel'
    | '/_app/painel-equipe'
    | '/_app/perfil'
    | '/_app/performance'
    | '/_app/produtos'
    | '/_app/ranking'
    | '/_app/seguradoras-parceiras'
    | '/_app/sem-permissao'
    | '/_app/usuarios'
    | '/_app/vendedores'
    | '/_auth/login'
    | '/_auth/recuperar-senha'
    | '/_auth/reset-senha'
    | '/_static/branding'
    | '/_static/certificado-preview'
    | '/_static/changelog'
    | '/_static/contato'
    | '/_static/cookies'
    | '/_static/funcionalidades'
    | '/_static/identidade-visual'
    | '/_static/lgpd'
    | '/_static/precos'
    | '/_static/privacidade'
    | '/_static/roadmap'
    | '/_static/sobre'
    | '/_static/termos'
    | '/_static/treinamentos'
    | '/embed/particles'
    | '/_admin/admin/audit-logs'
    | '/_admin/admin/backups'
    | '/_admin/admin/blog'
    | '/_admin/admin/changelogs'
    | '/_admin/admin/dashboard'
    | '/_admin/admin/login'
    | '/_admin/admin/perfil'
    | '/_admin/admin/pricing'
    | '/_admin/admin/roadmap'
    | '/_admin/admin/subscriptions'
    | '/_admin/admin/tenants'
    | '/_app/configuracoes/cargos'
    | '/_app/configuracoes/comissoes'
    | '/_app/configuracoes/corretora'
    | '/_app/dashboard/kanban'
    | '/_app/equipe/$id'
    | '/_app/importar-renovacoes/$importacaoId'
    | '/_app/importar-renovacoes/historico'
    | '/_app/metricas/renovacoes'
    | '/_app/pos-vendas/cross-selling'
    | '/_app/sinistro/kanban'
    | '/_static/blog/$slug'
    | '/_static/checkout/sucesso'
    | '/_static/docs/agenda'
    | '/_static/docs/clientes'
    | '/_static/docs/configuracoes'
    | '/_static/docs/cotacoes'
    | '/_static/docs/dashboard'
    | '/_static/docs/kanban'
    | '/_static/docs/metricas'
    | '/_static/docs/overview'
    | '/_static/docs/performance'
    | '/_static/docs/primeiros-passos'
    | '/_app/dashboard/'
    | '/_app/importar-renovacoes/'
    | '/_app/metricas/'
    | '/_app/sinistro/'
    | '/_app/workspace2/'
    | '/_static/blog/'
    | '/_static/checkout/'
    | '/_static/docs/'
    | '/_admin/admin/treinamentos/$cursoId'
    | '/_app/metricas/vendedor/$vendedorId'
    | '/_portal/portal/$subdominio/login'
    | '/_portal/portal/$subdominio/perfil'
    | '/_portal/portal/$subdominio/produtos'
    | '/_portal/portal/$subdominio/vencimentos'
    | '/_admin/admin/treinamentos/'
    | '/_portal/portal/$subdominio/'
    | '/_portal/portal/$subdominio/apolices/$id'
    | '/_portal/portal/$subdominio/apolices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  StaticRoute: typeof StaticRouteWithChildren
  EmbedParticlesRoute: typeof EmbedParticlesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_static': {
      id: '/_static'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StaticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/particles': {
      id: '/embed/particles'
      path: '/embed/particles'
      fullPath: '/embed/particles'
      preLoaderRoute: typeof EmbedParticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_static/treinamentos': {
      id: '/_static/treinamentos'
      path: '/treinamentos'
      fullPath: '/treinamentos'
      preLoaderRoute: typeof StaticTreinamentosRouteImport
      parentRoute: typeof StaticRoute
    }
    '/_static/termos': {
      id: '/_static/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof StaticTermosRouteImport
      parentRoute: typeof StaticRoute
    }
    '/_static/sobre': {
      id: '/_static/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof StaticSobreRouteImport
      parentRoute: typeof StaticRoute
    }
    '/_static/roadmap': {
      id: '/_static/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof StaticRoadmapRouteImport
      parentRoute: typeof StaticRoute
    }
    '/_static/privacidade': {
      id: '/_static/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof StaticPrivacidadeRouteImport
      parentRoute: typeof StaticRoute
    }
    '/_static/precos': {
      id: '/_static/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof StaticPrecosRouteImport
      parentRoute: typeof StaticRoute
    }
    '/_static/lgpd': {
      id: '/_static/lgpd'
      path: '/lgpd'
      fullPath: '/lgpd'
      preLoaderRoute: typeof StaticLgpdRouteImport
      parentRoute: typeof StaticRoute
    }
    '/_static/identidade-visual': {
      id: '/_static/identidade-visual'
      path: '/identidade-visual'
      fullPath: '/identidade-visual'
      preLoaderRoute: typeof StaticIdentidadeVisualRouteImport
      parentRoute: typeof StaticRoute
    }
    '/_static/funcionalidades': {
      id: '/_static/funcionalidades'
      path: '/funcionalidades'
      fullPath: '/funcionalidades'
      preLoaderRoute: typeof StaticFuncionalidadesRouteImport
      parentRoute: typeof StaticRoute
    }
    '/_static/cookies': {
      id: '/_static/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof StaticCookiesRouteImport
      parentRoute: typeof StaticRoute
    }
    '/_static/contato': {
      id: '/_static/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof StaticContatoRouteImport
      parentRoute: typeof StaticRoute
    }
    '/_static/changelog': {
      id: '/_static/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof StaticChangelogRouteImport
      parentRoute: typeof StaticRoute
    }
    '/_static/certificado-preview': {
      id: '/_static/certificado-preview'
      path: '/certificado-preview'
      fullPath: '/certificado-preview'
      preLoaderRoute: typeof StaticCertificadoPreviewRouteImport
      parentRoute: typeof StaticRoute
    }
    '/_static/branding': {
      id: '/_static/branding'
      path: '/branding'
      fullPath: '/branding'
      preLoaderRoute: typeof StaticBrandingRouteImport
      parentRoute: typeof StaticRoute
    }
    '/_auth/reset-senha': {
      id: '/_auth/reset-senha'
      path: '/reset-senha'
      fullPath: '/reset-senha'
      preLoaderRoute: typeof AuthResetSenhaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/recuperar-senha': {
      id: '/_auth/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof AuthRecuperarSenhaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/vendedores': {
      id: '/_app/vendedores'
      path: '/vendedores'
      fullPath: '/vendedores'
      preLoaderRoute: typeof AppVendedoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usuarios': {
      id: '/_app/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sem-permissao': {
      id: '/_app/sem-permissao'
      path: '/sem-permissao'
      fullPath: '/sem-permissao'
      preLoaderRoute: typeof AppSemPermissaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/seguradoras-parceiras': {
      id: '/_app/seguradoras-parceiras'
      path: '/seguradoras-parceiras'
      fullPath: '/seguradoras-parceiras'
      preLoaderRoute: typeof AppSeguradorasParceirasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ranking': {
      id: '/_app/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AppRankingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/produtos': {
      id: '/_app/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AppProdutosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/performance': {
      id: '/_app/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/painel-equipe': {
      id: '/_app/painel-equipe'
      path: '/painel-equipe'
      fullPath: '/painel-equipe'
      preLoaderRoute: typeof AppPainelEquipeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/painel': {
      id: '/_app/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AppPainelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notificacoes': {
      id: '/_app/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AppNotificacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/negocios': {
      id: '/_app/negocios'
      path: '/negocios'
      fullPath: '/negocios'
      preLoaderRoute: typeof AppNegociosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meu-desempenho': {
      id: '/_app/meu-desempenho'
      path: '/meu-desempenho'
      fullPath: '/meu-desempenho'
      preLoaderRoute: typeof AppMeuDesempenhoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketing': {
      id: '/_app/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AppMarketingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gestao': {
      id: '/_app/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof AppGestaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm': {
      id: '/_app/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cadastro': {
      id: '/_app/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof AppCadastroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_static/docs/': {
      id: '/_static/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof StaticDocsIndexRouteImport
      parentRoute: typeof StaticRoute
    }
    '/_static/checkout/': {
      id: '/_static/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof StaticCheckoutIndexRouteImport
      parentRoute: typeof StaticRoute
    }
    '/_static/blog/': {
      id: '/_static/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof StaticBlogIndexRouteImport
      parentRoute: typeof StaticRoute
    }
    '/_app/workspace2/': {
      id: '/_app/workspace2/'
      path: '/workspace2'
      fullPath: '/workspace2/'
      preLoaderRoute: typeof AppWorkspace2IndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sinistro/': {
      id: '/_app/sinistro/'
      path: '/sinistro'
      fullPath: '/sinistro/'
      preLoaderRoute: typeof AppSinistroIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metricas/': {
      id: '/_app/metricas/'
      path: '/metricas'
      fullPath: '/metricas/'
      preLoaderRoute: typeof AppMetricasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/importar-renovacoes/': {
      id: '/_app/importar-renovacoes/'
      path: '/importar-renovacoes'
      fullPath: '/importar-renovacoes/'
      preLoaderRoute: typeof AppImportarRenovacoesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_static/docs/primeiros-passos': {
      id: '/_static/docs/primeiros-passos'
      path: '/docs/primeiros-passos'
      fullPath: '/docs/primeiros-passos'
      preLoaderRoute: typeof StaticDocsPrimeirosPassosRouteImport
      parentRoute: typeof StaticRoute
    }
    '/_static/docs/performance': {
      id: '/_static/docs/performance'
      path: '/docs/performance'
      fullPath: '/docs/performance'
      preLoaderRoute: typeof StaticDocsPerformanceRouteImport
      parentRoute: typeof StaticRoute
    }
    '/_static/docs/overview': {
      id: '/_static/docs/overview'
      path: '/docs/overview'
      fullPath: '/docs/overview'
      preLoaderRoute: typeof StaticDocsOverviewRouteImport
      parentRoute: typeof StaticRoute
    }
    '/_static/docs/metricas': {
      id: '/_static/docs/metricas'
      path: '/docs/metricas'
      fullPath: '/docs/metricas'
      preLoaderRoute: typeof StaticDocsMetricasRouteImport
      parentRoute: typeof StaticRoute
    }
    '/_static/docs/kanban': {
      id: '/_static/docs/kanban'
      path: '/docs/kanban'
      fullPath: '/docs/kanban'
      preLoaderRoute: typeof StaticDocsKanbanRouteImport
      parentRoute: typeof StaticRoute
    }
    '/_static/docs/dashboard': {
      id: '/_static/docs/dashboard'
      path: '/docs/dashboard'
      fullPath: '/docs/dashboard'
      preLoaderRoute: typeof StaticDocsDashboardRouteImport
      parentRoute: typeof StaticRoute
    }
    '/_static/docs/cotacoes': {
      id: '/_static/docs/cotacoes'
      path: '/docs/cotacoes'
      fullPath: '/docs/cotacoes'
      preLoaderRoute: typeof StaticDocsCotacoesRouteImport
      parentRoute: typeof StaticRoute
    }
    '/_static/docs/configuracoes': {
      id: '/_static/docs/configuracoes'
      path: '/docs/configuracoes'
      fullPath: '/docs/configuracoes'
      preLoaderRoute: typeof StaticDocsConfiguracoesRouteImport
      parentRoute: typeof StaticRoute
    }
    '/_static/docs/clientes': {
      id: '/_static/docs/clientes'
      path: '/docs/clientes'
      fullPath: '/docs/clientes'
      preLoaderRoute: typeof StaticDocsClientesRouteImport
      parentRoute: typeof StaticRoute
    }
    '/_static/docs/agenda': {
      id: '/_static/docs/agenda'
      path: '/docs/agenda'
      fullPath: '/docs/agenda'
      preLoaderRoute: typeof StaticDocsAgendaRouteImport
      parentRoute: typeof StaticRoute
    }
    '/_static/checkout/sucesso': {
      id: '/_static/checkout/sucesso'
      path: '/checkout/sucesso'
      fullPath: '/checkout/sucesso'
      preLoaderRoute: typeof StaticCheckoutSucessoRouteImport
      parentRoute: typeof StaticRoute
    }
    '/_static/blog/$slug': {
      id: '/_static/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof StaticBlogSlugRouteImport
      parentRoute: typeof StaticRoute
    }
    '/_app/sinistro/kanban': {
      id: '/_app/sinistro/kanban'
      path: '/sinistro/kanban'
      fullPath: '/sinistro/kanban'
      preLoaderRoute: typeof AppSinistroKanbanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos-vendas/cross-selling': {
      id: '/_app/pos-vendas/cross-selling'
      path: '/pos-vendas/cross-selling'
      fullPath: '/pos-vendas/cross-selling'
      preLoaderRoute: typeof AppPosVendasCrossSellingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metricas/renovacoes': {
      id: '/_app/metricas/renovacoes'
      path: '/metricas/renovacoes'
      fullPath: '/metricas/renovacoes'
      preLoaderRoute: typeof AppMetricasRenovacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/importar-renovacoes/historico': {
      id: '/_app/importar-renovacoes/historico'
      path: '/importar-renovacoes/historico'
      fullPath: '/importar-renovacoes/historico'
      preLoaderRoute: typeof AppImportarRenovacoesHistoricoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/importar-renovacoes/$importacaoId': {
      id: '/_app/importar-renovacoes/$importacaoId'
      path: '/importar-renovacoes/$importacaoId'
      fullPath: '/importar-renovacoes/$importacaoId'
      preLoaderRoute: typeof AppImportarRenovacoesImportacaoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipe/$id': {
      id: '/_app/equipe/$id'
      path: '/equipe/$id'
      fullPath: '/equipe/$id'
      preLoaderRoute: typeof AppEquipeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/kanban': {
      id: '/_app/dashboard/kanban'
      path: '/dashboard/kanban'
      fullPath: '/dashboard/kanban'
      preLoaderRoute: typeof AppDashboardKanbanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes/corretora': {
      id: '/_app/configuracoes/corretora'
      path: '/configuracoes/corretora'
      fullPath: '/configuracoes/corretora'
      preLoaderRoute: typeof AppConfiguracoesCorretoraRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes/comissoes': {
      id: '/_app/configuracoes/comissoes'
      path: '/configuracoes/comissoes'
      fullPath: '/configuracoes/comissoes'
      preLoaderRoute: typeof AppConfiguracoesComissoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes/cargos': {
      id: '/_app/configuracoes/cargos'
      path: '/configuracoes/cargos'
      fullPath: '/configuracoes/cargos'
      preLoaderRoute: typeof AppConfiguracoesCargosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_admin/admin/tenants': {
      id: '/_admin/admin/tenants'
      path: '/admin/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminAdminTenantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/subscriptions': {
      id: '/_admin/admin/subscriptions'
      path: '/admin/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminAdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/roadmap': {
      id: '/_admin/admin/roadmap'
      path: '/admin/roadmap'
      fullPath: '/admin/roadmap'
      preLoaderRoute: typeof AdminAdminRoadmapRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/pricing': {
      id: '/_admin/admin/pricing'
      path: '/admin/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminAdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/perfil': {
      id: '/_admin/admin/perfil'
      path: '/admin/perfil'
      fullPath: '/admin/perfil'
      preLoaderRoute: typeof AdminAdminPerfilRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/login': {
      id: '/_admin/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminAdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/dashboard': {
      id: '/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/changelogs': {
      id: '/_admin/admin/changelogs'
      path: '/admin/changelogs'
      fullPath: '/admin/changelogs'
      preLoaderRoute: typeof AdminAdminChangelogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/blog': {
      id: '/_admin/admin/blog'
      path: '/admin/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminAdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/backups': {
      id: '/_admin/admin/backups'
      path: '/admin/backups'
      fullPath: '/admin/backups'
      preLoaderRoute: typeof AdminAdminBackupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/audit-logs': {
      id: '/_admin/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_portal/portal/$subdominio/': {
      id: '/_portal/portal/$subdominio/'
      path: '/portal/$subdominio'
      fullPath: '/portal/$subdominio/'
      preLoaderRoute: typeof PortalPortalSubdominioIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_admin/admin/treinamentos/': {
      id: '/_admin/admin/treinamentos/'
      path: '/admin/treinamentos'
      fullPath: '/admin/treinamentos/'
      preLoaderRoute: typeof AdminAdminTreinamentosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_portal/portal/$subdominio/vencimentos': {
      id: '/_portal/portal/$subdominio/vencimentos'
      path: '/portal/$subdominio/vencimentos'
      fullPath: '/portal/$subdominio/vencimentos'
      preLoaderRoute: typeof PortalPortalSubdominioVencimentosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/portal/$subdominio/produtos': {
      id: '/_portal/portal/$subdominio/produtos'
      path: '/portal/$subdominio/produtos'
      fullPath: '/portal/$subdominio/produtos'
      preLoaderRoute: typeof PortalPortalSubdominioProdutosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/portal/$subdominio/perfil': {
      id: '/_portal/portal/$subdominio/perfil'
      path: '/portal/$subdominio/perfil'
      fullPath: '/portal/$subdominio/perfil'
      preLoaderRoute: typeof PortalPortalSubdominioPerfilRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/portal/$subdominio/login': {
      id: '/_portal/portal/$subdominio/login'
      path: '/portal/$subdominio/login'
      fullPath: '/portal/$subdominio/login'
      preLoaderRoute: typeof PortalPortalSubdominioLoginRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_app/metricas/vendedor/$vendedorId': {
      id: '/_app/metricas/vendedor/$vendedorId'
      path: '/metricas/vendedor/$vendedorId'
      fullPath: '/metricas/vendedor/$vendedorId'
      preLoaderRoute: typeof AppMetricasVendedorVendedorIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_admin/admin/treinamentos/$cursoId': {
      id: '/_admin/admin/treinamentos/$cursoId'
      path: '/admin/treinamentos/$cursoId'
      fullPath: '/admin/treinamentos/$cursoId'
      preLoaderRoute: typeof AdminAdminTreinamentosCursoIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_portal/portal/$subdominio/apolices/': {
      id: '/_portal/portal/$subdominio/apolices/'
      path: '/portal/$subdominio/apolices'
      fullPath: '/portal/$subdominio/apolices/'
      preLoaderRoute: typeof PortalPortalSubdominioApolicesIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/portal/$subdominio/apolices/$id': {
      id: '/_portal/portal/$subdominio/apolices/$id'
      path: '/portal/$subdominio/apolices/$id'
      fullPath: '/portal/$subdominio/apolices/$id'
      preLoaderRoute: typeof PortalPortalSubdominioApolicesIdRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminAuditLogsRoute: typeof AdminAdminAuditLogsRoute
  AdminAdminBackupsRoute: typeof AdminAdminBackupsRoute
  AdminAdminBlogRoute: typeof AdminAdminBlogRoute
  AdminAdminChangelogsRoute: typeof AdminAdminChangelogsRoute
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminLoginRoute: typeof AdminAdminLoginRoute
  AdminAdminPerfilRoute: typeof AdminAdminPerfilRoute
  AdminAdminPricingRoute: typeof AdminAdminPricingRoute
  AdminAdminRoadmapRoute: typeof AdminAdminRoadmapRoute
  AdminAdminSubscriptionsRoute: typeof AdminAdminSubscriptionsRoute
  AdminAdminTenantsRoute: typeof AdminAdminTenantsRoute
  AdminAdminTreinamentosCursoIdRoute: typeof AdminAdminTreinamentosCursoIdRoute
  AdminAdminTreinamentosIndexRoute: typeof AdminAdminTreinamentosIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminAuditLogsRoute: AdminAdminAuditLogsRoute,
  AdminAdminBackupsRoute: AdminAdminBackupsRoute,
  AdminAdminBlogRoute: AdminAdminBlogRoute,
  AdminAdminChangelogsRoute: AdminAdminChangelogsRoute,
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminLoginRoute: AdminAdminLoginRoute,
  AdminAdminPerfilRoute: AdminAdminPerfilRoute,
  AdminAdminPricingRoute: AdminAdminPricingRoute,
  AdminAdminRoadmapRoute: AdminAdminRoadmapRoute,
  AdminAdminSubscriptionsRoute: AdminAdminSubscriptionsRoute,
  AdminAdminTenantsRoute: AdminAdminTenantsRoute,
  AdminAdminTreinamentosCursoIdRoute: AdminAdminTreinamentosCursoIdRoute,
  AdminAdminTreinamentosIndexRoute: AdminAdminTreinamentosIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppCadastroRoute: typeof AppCadastroRoute
  AppChatRoute: typeof AppChatRoute
  AppClientesRoute: typeof AppClientesRoute
  AppCrmRoute: typeof AppCrmRoute
  AppGestaoRoute: typeof AppGestaoRoute
  AppMarketingRoute: typeof AppMarketingRoute
  AppMeuDesempenhoRoute: typeof AppMeuDesempenhoRoute
  AppNegociosRoute: typeof AppNegociosRoute
  AppNotificacoesRoute: typeof AppNotificacoesRoute
  AppPainelRoute: typeof AppPainelRoute
  AppPainelEquipeRoute: typeof AppPainelEquipeRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppProdutosRoute: typeof AppProdutosRoute
  AppRankingRoute: typeof AppRankingRoute
  AppSeguradorasParceirasRoute: typeof AppSeguradorasParceirasRoute
  AppSemPermissaoRoute: typeof AppSemPermissaoRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppVendedoresRoute: typeof AppVendedoresRoute
  AppConfiguracoesCargosRoute: typeof AppConfiguracoesCargosRoute
  AppConfiguracoesComissoesRoute: typeof AppConfiguracoesComissoesRoute
  AppConfiguracoesCorretoraRoute: typeof AppConfiguracoesCorretoraRoute
  AppDashboardKanbanRoute: typeof AppDashboardKanbanRoute
  AppEquipeIdRoute: typeof AppEquipeIdRoute
  AppImportarRenovacoesImportacaoIdRoute: typeof AppImportarRenovacoesImportacaoIdRoute
  AppImportarRenovacoesHistoricoRoute: typeof AppImportarRenovacoesHistoricoRoute
  AppMetricasRenovacoesRoute: typeof AppMetricasRenovacoesRoute
  AppPosVendasCrossSellingRoute: typeof AppPosVendasCrossSellingRoute
  AppSinistroKanbanRoute: typeof AppSinistroKanbanRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppImportarRenovacoesIndexRoute: typeof AppImportarRenovacoesIndexRoute
  AppMetricasIndexRoute: typeof AppMetricasIndexRoute
  AppSinistroIndexRoute: typeof AppSinistroIndexRoute
  AppWorkspace2IndexRoute: typeof AppWorkspace2IndexRoute
  AppMetricasVendedorVendedorIdRoute: typeof AppMetricasVendedorVendedorIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppCadastroRoute: AppCadastroRoute,
  AppChatRoute: AppChatRoute,
  AppClientesRoute: AppClientesRoute,
  AppCrmRoute: AppCrmRoute,
  AppGestaoRoute: AppGestaoRoute,
  AppMarketingRoute: AppMarketingRoute,
  AppMeuDesempenhoRoute: AppMeuDesempenhoRoute,
  AppNegociosRoute: AppNegociosRoute,
  AppNotificacoesRoute: AppNotificacoesRoute,
  AppPainelRoute: AppPainelRoute,
  AppPainelEquipeRoute: AppPainelEquipeRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppPerformanceRoute: AppPerformanceRoute,
  AppProdutosRoute: AppProdutosRoute,
  AppRankingRoute: AppRankingRoute,
  AppSeguradorasParceirasRoute: AppSeguradorasParceirasRoute,
  AppSemPermissaoRoute: AppSemPermissaoRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppVendedoresRoute: AppVendedoresRoute,
  AppConfiguracoesCargosRoute: AppConfiguracoesCargosRoute,
  AppConfiguracoesComissoesRoute: AppConfiguracoesComissoesRoute,
  AppConfiguracoesCorretoraRoute: AppConfiguracoesCorretoraRoute,
  AppDashboardKanbanRoute: AppDashboardKanbanRoute,
  AppEquipeIdRoute: AppEquipeIdRoute,
  AppImportarRenovacoesImportacaoIdRoute:
    AppImportarRenovacoesImportacaoIdRoute,
  AppImportarRenovacoesHistoricoRoute: AppImportarRenovacoesHistoricoRoute,
  AppMetricasRenovacoesRoute: AppMetricasRenovacoesRoute,
  AppPosVendasCrossSellingRoute: AppPosVendasCrossSellingRoute,
  AppSinistroKanbanRoute: AppSinistroKanbanRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppImportarRenovacoesIndexRoute: AppImportarRenovacoesIndexRoute,
  AppMetricasIndexRoute: AppMetricasIndexRoute,
  AppSinistroIndexRoute: AppSinistroIndexRoute,
  AppWorkspace2IndexRoute: AppWorkspace2IndexRoute,
  AppMetricasVendedorVendedorIdRoute: AppMetricasVendedorVendedorIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRecuperarSenhaRoute: typeof AuthRecuperarSenhaRoute
  AuthResetSenhaRoute: typeof AuthResetSenhaRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRecuperarSenhaRoute: AuthRecuperarSenhaRoute,
  AuthResetSenhaRoute: AuthResetSenhaRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PortalRouteChildren {
  PortalPortalSubdominioLoginRoute: typeof PortalPortalSubdominioLoginRoute
  PortalPortalSubdominioPerfilRoute: typeof PortalPortalSubdominioPerfilRoute
  PortalPortalSubdominioProdutosRoute: typeof PortalPortalSubdominioProdutosRoute
  PortalPortalSubdominioVencimentosRoute: typeof PortalPortalSubdominioVencimentosRoute
  PortalPortalSubdominioIndexRoute: typeof PortalPortalSubdominioIndexRoute
  PortalPortalSubdominioApolicesIdRoute: typeof PortalPortalSubdominioApolicesIdRoute
  PortalPortalSubdominioApolicesIndexRoute: typeof PortalPortalSubdominioApolicesIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalPortalSubdominioLoginRoute: PortalPortalSubdominioLoginRoute,
  PortalPortalSubdominioPerfilRoute: PortalPortalSubdominioPerfilRoute,
  PortalPortalSubdominioProdutosRoute: PortalPortalSubdominioProdutosRoute,
  PortalPortalSubdominioVencimentosRoute:
    PortalPortalSubdominioVencimentosRoute,
  PortalPortalSubdominioIndexRoute: PortalPortalSubdominioIndexRoute,
  PortalPortalSubdominioApolicesIdRoute: PortalPortalSubdominioApolicesIdRoute,
  PortalPortalSubdominioApolicesIndexRoute:
    PortalPortalSubdominioApolicesIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface StaticRouteChildren {
  StaticBrandingRoute: typeof StaticBrandingRoute
  StaticCertificadoPreviewRoute: typeof StaticCertificadoPreviewRoute
  StaticChangelogRoute: typeof StaticChangelogRoute
  StaticContatoRoute: typeof StaticContatoRoute
  StaticCookiesRoute: typeof StaticCookiesRoute
  StaticFuncionalidadesRoute: typeof StaticFuncionalidadesRoute
  StaticIdentidadeVisualRoute: typeof StaticIdentidadeVisualRoute
  StaticLgpdRoute: typeof StaticLgpdRoute
  StaticPrecosRoute: typeof StaticPrecosRoute
  StaticPrivacidadeRoute: typeof StaticPrivacidadeRoute
  StaticRoadmapRoute: typeof StaticRoadmapRoute
  StaticSobreRoute: typeof StaticSobreRoute
  StaticTermosRoute: typeof StaticTermosRoute
  StaticTreinamentosRoute: typeof StaticTreinamentosRoute
  StaticBlogSlugRoute: typeof StaticBlogSlugRoute
  StaticCheckoutSucessoRoute: typeof StaticCheckoutSucessoRoute
  StaticDocsAgendaRoute: typeof StaticDocsAgendaRoute
  StaticDocsClientesRoute: typeof StaticDocsClientesRoute
  StaticDocsConfiguracoesRoute: typeof StaticDocsConfiguracoesRoute
  StaticDocsCotacoesRoute: typeof StaticDocsCotacoesRoute
  StaticDocsDashboardRoute: typeof StaticDocsDashboardRoute
  StaticDocsKanbanRoute: typeof StaticDocsKanbanRoute
  StaticDocsMetricasRoute: typeof StaticDocsMetricasRoute
  StaticDocsOverviewRoute: typeof StaticDocsOverviewRoute
  StaticDocsPerformanceRoute: typeof StaticDocsPerformanceRoute
  StaticDocsPrimeirosPassosRoute: typeof StaticDocsPrimeirosPassosRoute
  StaticBlogIndexRoute: typeof StaticBlogIndexRoute
  StaticCheckoutIndexRoute: typeof StaticCheckoutIndexRoute
  StaticDocsIndexRoute: typeof StaticDocsIndexRoute
}

const StaticRouteChildren: StaticRouteChildren = {
  StaticBrandingRoute: StaticBrandingRoute,
  StaticCertificadoPreviewRoute: StaticCertificadoPreviewRoute,
  StaticChangelogRoute: StaticChangelogRoute,
  StaticContatoRoute: StaticContatoRoute,
  StaticCookiesRoute: StaticCookiesRoute,
  StaticFuncionalidadesRoute: StaticFuncionalidadesRoute,
  StaticIdentidadeVisualRoute: StaticIdentidadeVisualRoute,
  StaticLgpdRoute: StaticLgpdRoute,
  StaticPrecosRoute: StaticPrecosRoute,
  StaticPrivacidadeRoute: StaticPrivacidadeRoute,
  StaticRoadmapRoute: StaticRoadmapRoute,
  StaticSobreRoute: StaticSobreRoute,
  StaticTermosRoute: StaticTermosRoute,
  StaticTreinamentosRoute: StaticTreinamentosRoute,
  StaticBlogSlugRoute: StaticBlogSlugRoute,
  StaticCheckoutSucessoRoute: StaticCheckoutSucessoRoute,
  StaticDocsAgendaRoute: StaticDocsAgendaRoute,
  StaticDocsClientesRoute: StaticDocsClientesRoute,
  StaticDocsConfiguracoesRoute: StaticDocsConfiguracoesRoute,
  StaticDocsCotacoesRoute: StaticDocsCotacoesRoute,
  StaticDocsDashboardRoute: StaticDocsDashboardRoute,
  StaticDocsKanbanRoute: StaticDocsKanbanRoute,
  StaticDocsMetricasRoute: StaticDocsMetricasRoute,
  StaticDocsOverviewRoute: StaticDocsOverviewRoute,
  StaticDocsPerformanceRoute: StaticDocsPerformanceRoute,
  StaticDocsPrimeirosPassosRoute: StaticDocsPrimeirosPassosRoute,
  StaticBlogIndexRoute: StaticBlogIndexRoute,
  StaticCheckoutIndexRoute: StaticCheckoutIndexRoute,
  StaticDocsIndexRoute: StaticDocsIndexRoute,
}

const StaticRouteWithChildren =
  StaticRoute._addFileChildren(StaticRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  StaticRoute: StaticRouteWithChildren,
  EmbedParticlesRoute: EmbedParticlesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
